// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// unnamed API: Application Contexts
//
// Command:
// $ goagen
// --design=github.com/kovetskiy/goatest/design
// --out=$(GOPATH)/src/github.com/kovetskiy/goatest
// --version=v1.3.0

package app

import (
	"context"
	"github.com/goadesign/goa"
	"net/http"
)

// GetSomeContext provides the some get action context.
type GetSomeContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
}

// NewGetSomeContext parses the incoming request URL and body, performs validations and creates the
// context used by the some controller get action.
func NewGetSomeContext(ctx context.Context, r *http.Request, service *goa.Service) (*GetSomeContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := GetSomeContext{Context: ctx, ResponseData: resp, RequestData: req}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *GetSomeContext) OK(r *SomeData) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/vnd.some.data+json")
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}
