// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// unnamed API: Application User Types
//
// Command:
// $ goagen
// --design=github.com/kovetskiy/goatest/design
// --out=$(GOPATH)/src/github.com/kovetskiy/goatest
// --version=v1.3.0

package app
